import { Link, useParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, Building2, Home, Landmark } from "lucide-react";
import { PublicShell } from "@/features/marketing/components/PublicShell";
import { Button } from "@/shared/components/ui/button";
import { DEFAULT_PUBLIC_SITE_CONFIG } from "@/features/marketing/publicSiteConfig";
import { PROPERTY_IMAGES } from "@/features/marketing/propertyImages";

const LABELS: Record<string, { title: string; copy: string; image: string; icon: typeof Home }> = {
  residential: { title: "Residential properties", copy: "Explore homes, apartments and rental communities. When live listings are published, this page becomes the public residential discovery surface.", image: PROPERTY_IMAGES.residential, icon: Home },
  estates: { title: "Estates", copy: "Explore managed estates and multi-unit communities. Featured and live adverts can be routed here from the homepage.", image: PROPERTY_IMAGES.commercial, icon: Building2 },
  offices: { title: "Office properties", copy: "Explore offices and professional workspaces. Live public inventory can be connected without changing the homepage design.", image: PROPERTY_IMAGES.office, icon: Building2 },
  institutions: { title: "Institutional properties", copy: "Explore purpose-built property portfolios and facilities. This discovery route is ready for published inventory.", image: PROPERTY_IMAGES.commercial, icon: Landmark },
};

export default function PublicPropertyDiscoveryPage() {
  const { category = "residential" } = useParams();
  const current = LABELS[category] || LABELS.residential;
  const Icon = current.icon;
  const featured = DEFAULT_PUBLIC_SITE_CONFIG.featured.filter((item) => item.href.includes(category)).filter((item) => item.enabled);
  return <PublicShell><section className="relative overflow-hidden bg-navy-deep text-white"><div className="absolute inset-0"><img src={current.image} alt="" className="h-full w-full object-cover opacity-45"/><div className="absolute inset-0 bg-gradient-to-r from-navy-deep via-navy-deep/80 to-navy-deep/25"/></div><div className="relative mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><Button asChild variant="ghost" className="mb-8 -ml-3 text-white/70 hover:bg-white/10 hover:text-white"><Link to="/"><ArrowLeft className="mr-2 h-4 w-4"/>Back to CALQULUS</Link></Button><div className="max-w-2xl"><span className="inline-flex h-11 w-11 items-center justify-center rounded-xl border border-white/15 bg-white/10"><Icon className="h-5 w-5"/></span><p className="mt-6 text-[11px] font-semibold tracking-[.2em] text-success">PROPERTY DISCOVERY</p><h1 className="mt-2 font-heading text-4xl font-semibold tracking-[-.04em] sm:text-6xl">{current.title}</h1><p className="mt-5 text-base leading-7 text-white/70 sm:text-lg">{current.copy}</p></div></div></section><section className="bg-background py-16 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-semibold tracking-[.2em] text-primary">SALE & LETTING</p><h2 className="mt-2 font-heading text-3xl font-semibold tracking-tight">Available listings will appear here.</h2></div><p className="max-w-md text-sm leading-6 text-muted-foreground sm:text-right">The route is intentionally live-data ready. No private manager portfolio records are exposed publicly.</p></div>{featured.length ? <div className="mt-10 grid gap-5 md:grid-cols-3">{featured.map((item)=><Link key={item.id} to={item.href} className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm hover:shadow-lg"><img src={item.image || current.image} alt="" className="aspect-[16/10] w-full object-cover"/><div className="p-5"><p className="text-xs text-primary">{item.location}</p><h3 className="mt-1 font-heading text-lg font-semibold">{item.title}</h3><p className="mt-2 text-sm text-muted-foreground">{item.detail}</p><p className="mt-4 text-sm font-semibold">{item.price}</p></div></Link>)}</div> : <div className="mt-10 rounded-2xl border border-dashed border-border bg-card p-8 sm:p-12"><p className="text-sm leading-6 text-muted-foreground">There are no published {category} adverts yet. Once a real advert is activated in Public Site Studio, the homepage and this discovery surface can point visitors to it.</p><Button asChild className="btn-brand mt-5"><Link to="/">Return home <ArrowRight className="ml-2 h-4 w-4"/></Link></Button></div>}</div></section></PublicShell>;
}
