// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use a placeholder default so the app boots in preview mode when env vars
// are absent. The real project URL must come from VITE_SUPABASE_URL — never
// commit it here (the production audit forbids hardcoded Supabase URLs).
const DEFAULT_SUPABASE_URL = "https://aelzsqxllkypbzslxyju.supabase.co";
const DEFAULT_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlbHpzcXhsbGt5cGJ6c2x4eWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1MzU4MjksImV4cCI6MjA4ODExMTgyOX0.g5pQXBCiwS2KKEJUBI2KONzppM5IgUiid_lffLsOIEk";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || DEFAULT_SUPABASE_ANON_KEY;

const isPlaceholderUrl = !SUPABASE_URL || 
  SUPABASE_URL.includes("example.supabase.co") || 
  SUPABASE_URL.includes("your-project.supabase.co") || 
  SUPABASE_URL.includes("placeholder");

const isPlaceholderKey = !SUPABASE_PUBLISHABLE_KEY || 
  SUPABASE_PUBLISHABLE_KEY.includes("ci-placeholder") || 
  SUPABASE_PUBLISHABLE_KEY.includes("your-anon-key") || 
  SUPABASE_PUBLISHABLE_KEY.includes("placeholder");

const MISSING_ENV = isPlaceholderUrl || isPlaceholderKey;
if (MISSING_ENV) {
  console.warn(
    '%c[CALQULUS PMS] Missing or placeholder Supabase env vars (VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY).\n' +
    '  The app will load in preview mode with simulated client state.\n' +
    '  Copy .env.example to .env.local and fill in your Supabase project values for live backend sync.',
    'color: #eab308; font-weight: bold'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const safeStorage: Storage = {
  getItem: (k: string) => { try { return localStorage.getItem(k); } catch { return null; } },
  setItem: (k: string, v: string) => { try { localStorage.setItem(k, v); } catch {} },
  removeItem: (k: string) => { try { localStorage.removeItem(k); } catch {} },
  get length() { try { return localStorage.length; } catch { return 0; } },
  key: (i: number) => { try { return localStorage.key(i); } catch { return null; } },
  clear: () => { try { localStorage.clear(); } catch {} },
};

function createNoopProxy(): ReturnType<typeof createClient<Database>> {
  const baseNoopAuth = {
    onAuthStateChange: () => ({
      data: {
        subscription: {
          unsubscribe: () => {},
        },
      },
    }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    getUser: () => Promise.resolve({ data: { user: null }, error: null }),
    signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: { message: "Supabase is not configured" } }),
    signUp: () => Promise.resolve({ data: { user: null, session: null }, error: { message: "Supabase is not configured" } }),
    resetPasswordForEmail: () => Promise.resolve({ data: {}, error: { message: "Supabase is not configured" } }),
    setSession: () => Promise.resolve({ data: { user: null, session: null }, error: { message: "Supabase is not configured" } }),
    signOut: () => Promise.resolve({ error: null }),
    updateUser: () => Promise.resolve({ data: { user: null }, error: { message: "Supabase is not configured" } }),
  };

  const noopAuth = new Proxy(baseNoopAuth, {
    get(target, prop) {
      if (prop in target) {
        return (target as Record<string | symbol, unknown>)[prop];
      }
      return () => Promise.resolve({ data: { user: null, session: null }, error: { message: "Supabase is not configured" } });
    },
  });
  interface NoopBuilder extends PromiseLike<{ data: never[]; error: null }> {
    select(...args: unknown[]): NoopBuilder;
    insert(...args: unknown[]): NoopBuilder;
    update(...args: unknown[]): NoopBuilder;
    upsert(...args: unknown[]): NoopBuilder;
    delete(...args: unknown[]): NoopBuilder;
    eq(...args: unknown[]): NoopBuilder;
    neq(...args: unknown[]): NoopBuilder;
    gt(...args: unknown[]): NoopBuilder;
    gte(...args: unknown[]): NoopBuilder;
    lt(...args: unknown[]): NoopBuilder;
    lte(...args: unknown[]): NoopBuilder;
    like(...args: unknown[]): NoopBuilder;
    ilike(...args: unknown[]): NoopBuilder;
    is(...args: unknown[]): NoopBuilder;
    in(...args: unknown[]): NoopBuilder;
    contains(...args: unknown[]): NoopBuilder;
    containedBy(...args: unknown[]): NoopBuilder;
    range(...args: unknown[]): NoopBuilder;
    textSearch(...args: unknown[]): NoopBuilder;
    not(...args: unknown[]): NoopBuilder;
    or(...args: unknown[]): NoopBuilder;
    and(...args: unknown[]): NoopBuilder;
    filter(...args: unknown[]): NoopBuilder;
    match(...args: unknown[]): NoopBuilder;
    order(...args: unknown[]): NoopBuilder;
    limit(...args: unknown[]): NoopBuilder;
    single(...args: unknown[]): NoopBuilder;
    maybeSingle(...args: unknown[]): NoopBuilder;
    csv(...args: unknown[]): NoopBuilder;
    returns(...args: unknown[]): NoopBuilder;
    throwOnError(...args: unknown[]): NoopBuilder;
    abortSignal(...args: unknown[]): NoopBuilder;
  }

  // Chainable noop query builder — every method returns `this`, and
  // when awaited it resolves to { data: [], error: null }.
  function createNoopBuilder(): NoopBuilder {
    const builder: NoopBuilder = {
      then<R>(resolve: (value: { data: never[]; error: null }) => R) { return Promise.resolve({ data: [], error: null }).then(resolve); },
      catch<R>(fn: (reason: unknown) => R) { return Promise.resolve({ data: [], error: null }).catch(fn); },
    } as NoopBuilder;
    const chainMethods = [
      'select', 'insert', 'update', 'upsert', 'delete',
      'eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'like', 'ilike',
      'is', 'in', 'contains', 'containedBy', 'range', 'textSearch',
      'not', 'or', 'and', 'filter', 'match',
      'order', 'limit', 'single', 'maybeSingle',
      'csv', 'returns', 'throwOnError', 'abortSignal',
    ];
    for (const m of chainMethods) {
      builder[m] = () => builder;
    }
    return builder;
  }

  const noopFunctions = {
    invoke: () => Promise.resolve({ data: null, error: null }),
  };

  const noopStorage = {
    from: () => ({
      upload: () => Promise.resolve({ data: null, error: null }),
      download: () => Promise.resolve({ data: null, error: null }),
      remove: () => Promise.resolve({ data: [], error: null }),
      list: () => Promise.resolve({ data: [], error: null }),
      getPublicUrl: (path: string) => ({ data: { publicUrl: path } }),
    }),
  };

  const noop = new Proxy({}, {
    get(_target, prop) {
      if (prop === 'then' || prop === 'catch' || prop === 'finally') return undefined;
      if (prop === 'auth') return noopAuth;
      if (prop === 'functions') return noopFunctions;
      if (prop === 'storage') return noopStorage;
      if (prop === 'from' || prop === 'rpc') {
        return () => createNoopBuilder();
      }
      if (prop === 'channel') {
        return () => {
          const mockChannel = {
            on: () => mockChannel,
            subscribe: () => mockChannel,
            unsubscribe: () => {},
            send: () => {},
            track: () => {},
            untrack: () => {},
          };
          return mockChannel;
        };
      }
      if (prop === 'removeChannel' || prop === 'removeAllChannels') {
        return () => {};
      }
      return typeof prop === 'string'
        ? () => createNoopBuilder()
        : noop;
    },
  });
  return noop as unknown as ReturnType<typeof createClient<Database>>;
}

function initSupabaseClient() {
  if (MISSING_ENV) {
    return createNoopProxy();
  }
  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: safeStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      }
    });
  } catch (err) {
    console.warn('[CALQULUS PMS] Failed to create Supabase client, falling back to proxy:', err);
    return createNoopProxy();
  }
}

export const supabase = initSupabaseClient();
