// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const MISSING_ENV = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;
if (MISSING_ENV) {
  console.warn(
    '%c[RentFlow] Missing Supabase env vars (VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY).\n' +
    '  The app will load but auth and data features will be unavailable.\n' +
    '  Copy .env.example to .env.local and fill in your Supabase project values.',
    'color: #eab308; font-weight: bold'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const safeStorage: Storage = {
  getItem: (k: string) => { try { return localStorage.getItem(k); } catch { return null; } },
  setItem: (k: string, v: string) => { try { localStorage.setItem(k, v); } catch {} },
  removeItem: (k: string) => { try { localStorage.removeItem(k); } catch {} },
  get length() { try { return localStorage.length; } catch { return 0; } },
  key: (i: number) => { try { return localStorage.key(i); } catch { return null; } },
  clear: () => { try { localStorage.clear(); } catch {} },
};

function createNoopProxy(): ReturnType<typeof createClient<Database>> {
  const noop = new Proxy({}, {
    get(_target, prop) {
      if (prop === 'then' || prop === 'catch' || prop === 'finally') return undefined;
      return typeof prop === 'string' && prop !== 'then'
        ? (...args: unknown[]) => {
            const result = Array.isArray(args[0]) ? [] : {};
            return Promise.resolve({ data: result, error: null });
          }
        : noop;
    },
  });
  return noop as unknown as ReturnType<typeof createClient<Database>>;
}

export const supabase = MISSING_ENV
  ? createNoopProxy()
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: safeStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
